<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="0" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-21T16:32:57 IST" name="Suite" finished-at="2024-04-21T16:34:00 IST" duration-ms="63190">
    <groups>
      <group name="rail_regression">
        <method signature="searchTrainTest.searchTrain()[pri:0, instance:com.nagarro.nagp.testpackage.searchTrainTest@1133ec6e]" name="searchTrain" class="com.nagarro.nagp.testpackage.searchTrainTest"/>
      </group> <!-- rail_regression -->
    </groups>
    <test started-at="2024-04-21T16:32:57 IST" name="Test" finished-at="2024-04-21T16:34:00 IST" duration-ms="63190">
      <class name="com.nagarro.nagp.testpackage.searchTrainTest">
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:com.nagarro.nagp.testpackage.searchTrainTest@1133ec6e]" started-at="2024-04-21T16:32:57 IST" name="launchBrowser" finished-at="2024-04-21T16:33:07 IST" duration-ms="9700" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method retried="true" signature="searchTrain()[pri:0, instance:com.nagarro.nagp.testpackage.searchTrainTest@1133ec6e]" started-at="2024-04-21T16:33:07 IST" name="searchTrain" description="Validate the user can search the live status of a train" finished-at="2024-04-21T16:33:17 IST" duration-ms="10437" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Some issue in getting train live status expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Some issue in getting train live status expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.nagarro.nagp.testpackage.searchTrainTest.searchTrain(searchTrainTest.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchTrain -->
        <test-method is-config="true" signature="afterMethodTearDown()[pri:0, instance:com.nagarro.nagp.testpackage.searchTrainTest@1133ec6e]" started-at="2024-04-21T16:33:17 IST" name="afterMethodTearDown" finished-at="2024-04-21T16:33:17 IST" duration-ms="316" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodTearDown -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:com.nagarro.nagp.testpackage.searchTrainTest@1133ec6e]" started-at="2024-04-21T16:33:17 IST" name="launchBrowser" finished-at="2024-04-21T16:33:25 IST" duration-ms="7443" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method retried="true" signature="searchTrain()[pri:0, instance:com.nagarro.nagp.testpackage.searchTrainTest@1133ec6e]" started-at="2024-04-21T16:33:25 IST" name="searchTrain" description="Validate the user can search the live status of a train" finished-at="2024-04-21T16:33:35 IST" duration-ms="9972" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Some issue in getting train live status expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Some issue in getting train live status expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.nagarro.nagp.testpackage.searchTrainTest.searchTrain(searchTrainTest.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchTrain -->
        <test-method is-config="true" signature="afterMethodTearDown()[pri:0, instance:com.nagarro.nagp.testpackage.searchTrainTest@1133ec6e]" started-at="2024-04-21T16:33:35 IST" name="afterMethodTearDown" finished-at="2024-04-21T16:33:35 IST" duration-ms="333" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodTearDown -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:com.nagarro.nagp.testpackage.searchTrainTest@1133ec6e]" started-at="2024-04-21T16:33:35 IST" name="launchBrowser" finished-at="2024-04-21T16:33:50 IST" duration-ms="15137" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="searchTrain()[pri:0, instance:com.nagarro.nagp.testpackage.searchTrainTest@1133ec6e]" started-at="2024-04-21T16:33:50 IST" name="searchTrain" description="Validate the user can search the live status of a train" finished-at="2024-04-21T16:34:00 IST" duration-ms="9342" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Some issue in getting train live status expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Some issue in getting train live status expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.nagarro.nagp.testpackage.searchTrainTest.searchTrain(searchTrainTest.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchTrain -->
        <test-method is-config="true" signature="afterMethodTearDown()[pri:0, instance:com.nagarro.nagp.testpackage.searchTrainTest@1133ec6e]" started-at="2024-04-21T16:34:00 IST" name="afterMethodTearDown" finished-at="2024-04-21T16:34:00 IST" duration-ms="305" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodTearDown -->
      </class> <!-- com.nagarro.nagp.testpackage.searchTrainTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
